### ISSUE TITLE
Support for less files

### ISSUE THREAD

**Issue by dloop-mb** [Siilwyn/prettier-plugin-css-order#12]
In the current version there is only support for scss files, although [css-declaration-order](https://github.com/Siilwyn/css-declaration-sorter/) supports less as well.
I have created a small [PR](https://github.com/Siilwyn/prettier-plugin-css-order/pull/11) for this. Please check it out and let me know if there are any issues or if it can be integrated.

**Comment by Siilwyn** [comment]
Closed by 6540863a75aad456d85ab8f233878067215f06c6
