### ISSUE TITLE
Consider renaming the configuration options name and changing the default value

### ISSUE THREAD

**Issue by chalkygames123** [Siilwyn/prettier-plugin-css-order#22]
Hi 👋

Why don't you add a prefix to the plugin-specific configuration options, as most of [the official plugins](https://prettier.io/docs/en/plugins.html#official-plugins) below do?

- https://prettier.github.io/plugin-pug/guide/standard-prettier-overrides.html
- https://github.com/prettier/plugin-ruby#configuration
- https://github.com/prettier/plugin-xml#configuration

Also, changing the default value to `true` might be a good idea while we're on the subject of a breaking change.

**Comment by pauldraper** [comment]
I agree, I recommend

```
cssDeclarationSorterOrder
cssDeclarationSorterKeepOverrides
```

And using the defaults from that project.

This project is more or less a integration between prettier and css-declaration-sorter; I don't see a reason to add any abstraction over that.

**Comment by Siilwyn** [comment]
Will release this in 2.0 :tada:
