### ISSUE TITLE
Yarn Berry compatibility

### ISSUE THREAD

**Issue by bronisMateusz** [Siilwyn/prettier-plugin-css-order#26]
When I used your sorter with Vue.js 3 and yarn version `1.22.19`, everything worked great. I upgraded to `3.6.0` and when calling the `prettier --write src/` command I get a warning:

`[warn] Ignored unknown option { order: "alphabetical" }.`

This is my `.prettierrc.json` file:

```
{
  "$schema": "https://json.schemastore.org/prettierrc",
  "semi": false,
  "tabWidth": 2,
  "singleQuote": true,
  "printWidth": 100,
  "trailingComma": "none",
  "order": "alphabetical"
}
```

**Comment by Siilwyn** [comment]
:wave: sorry for the late reply, I don't have experience with Yarn Berry but I wonder if the Prettier 3 upgrade fixed this. Please let me know, I'll gladly re-open this and accept a PR.
