### ISSUE TITLE
Compatiblity with Prettier 3.0

### ISSUE THREAD

**Issue by jablonski** [Siilwyn/prettier-plugin-css-order#27]
At the moment it is not possible to use the plugin with Prettier 3.x. Current peerDependency in package.json is 2.x.

**Comment by Siilwyn** [comment]
Will release this in 2.0 :tada:

**Comment by scmx** [comment]
```
Cannot find module 'css-declaration-sorter/src/bubble-sort.mjs' imported from css-declaration-sorter/src/main.mjs
```
@Siilwyn looks like something may be wrong. Great plugin btw ⭐ 
I ran
`npx prettier --plugin prettier-plugin-css-order style.scss`
with
"prettier": "^3.0.1",
"prettier-plugin-css-order": "^2.0.0" that brings in "css-declaration-sorter": "7.0.0",

(Also, you might want to mention in readme that prettier now expects you to explicitly enable the plugin https://prettier.io/docs/en/plugins)
```
{
  "plugins": ["prettier-plugin-css-order"]
}

**Comment by Siilwyn** [comment]
@scmx :wave: this should be fixed in version 7.0.2 of css-declaration-sorter, could you test if upgrading resolves it?

**Comment by scmx** [comment]
Yes it worked when I did `npm i -D css-declaration-sorter`. But not without adding it as a direct dependency.

**Comment by Siilwyn** [comment]
@scmx yes that would force the latest version, now if you remove it with `npm rm` it should still use the latest version I think, could you give that a try?
