### ISSUE TITLE
Incorrect description of npm package

### ISSUE THREAD

**Issue by xeqtr-zhg** [Siilwyn/prettier-plugin-css-order#34]
Greetings, on the npmjs add-on page (https://www.npmjs.com/package/prettier-plugin-css-order) the description says that after installation the plugin will start working immediately, this is not true, on your github page (https://github.com/Siilwyn/prettier-plugin-css-order/) the description is correct. This may mislead some npmjs users, please correct the description, thanks.

**Comment by Siilwyn** [comment]
Fixed!
