### ISSUE TITLE
security vulnerability PostCSS

### ISSUE THREAD

**Issue by dogangok** [Siilwyn/prettier-plugin-css-order#38]
It seems like you're dealing with a security vulnerability in a dependency of your project.
Unfortunately, there's no direct fix available for the version of PostCSS you're using.
Would you be so kind to update the dependencies that rely on the vulnerable version of PostCSS.
In this case update postcss@7.0.39 to postcss@8.4.32.

**Comment by Siilwyn** [comment]
Postcss 8 is a peer dependency and isn't locked to a version, certainly not 7. You can update to 8 if wanted.
