### ISSUE TITLE
New mode for sorting

### ISSUE THREAD

**Issue by SavaCool122** [Siilwyn/prettier-plugin-css-order#39]
Huge thank you for this beautiful plugin. I am very happy to use it. On the last project I ran into a problem that I can't set the sort order the way I want (I have my own opinion on how I want to sort the rules on the project).

After researching and looking at the implementation, I realized that this can't be done in the current implementation. It would be great if such an opportunity appeared. For example, how does [hudochenkov/stylelint-order](https://github.com/hudochenkov/stylelint-order) do it. Also see example of usage: [.stylelintrc.yml](https://github.com/pepelsbey/pepelsbey.dev/blob/main/.stylelintrc.yml)

In general it will looks like this:

1. Add new option in configuration:

`cssDeclarationSorterOrder` -> `choices` ->

```js
[
{
  value: "alphabetical",
  description:
	"Default, order in a simple alphabetical manner from a - z.",
},
{
  value: "smacss",
  description:
	"Order from most important, flow affecting properties, to least important properties.",
},
{
  value: "concentric-css",
  description:
		"Order properties applying outside the box model, moving inward to intrinsic changes.",
},
{
  value: "custom", // new custom mode 
  description:
	"Provide an array of declaration names in the `customOrder` property.", 
},
],
```

2. New property for this option `customOrder` that takes array of strings

3. For the end user, it will look like this

```js
const myOrder = [
	"margin-inline-start",
	"margin-inline-end",
	"padding",
	"padding-top",
	"padding-right",
	"flex"
]

export default {
	plugins: ["prettier-plugin-css-order"],
	cssDeclarationSorterOrder: "custom",
	customOrder: myOrder,
};
```

This improvement would help me to continue using your plugin.

**Comment by Siilwyn** [comment]
:wave: I'm open for a PR to support passing an array to the `[cssDeclarationSorterOrder](https://github.com/Siilwyn/css-declaration-sorter#order)` option in this project. You'll need to write a function in `prettier-plugin-css-order` which uses this array, and then pass this function to `css-declaration-sorter`.

This is because passing a function isn't supported by Prettier, see: https://github.com/Siilwyn/prettier-plugin-css-order/issues/16

**Comment by SavaCool122** [comment]
Thanks for the quick response. I have already encountered a restriction on passing a function. Yes, I saw that prettier doesn't allow passing functions. That's why I suggested passing an array.
I already have an implementation. I just need some time to pass it to you as a PR.

**Comment by SavaCool122** [comment]
And here's the PR. Using the existing code, it is not easy to understand the style of writing code in a project. Therefore, I am open to any edits and additional tests.

**Comment by Siilwyn** [comment]
@SavaCool122 hey sorry, been busy: Put a comment on the PR!
