### ISSUE TITLE
postcss in install instructions

### ISSUE THREAD

**Issue by receter** [Siilwyn/prettier-plugin-css-order#45]
Is postcss still a dependency? Its's no in the `peerDependencies`, but it is in the install script in the README.

I am asking because I am not sure if I really need to install it. It works without explicitly installing it for me, but I use Vite so postcss is installed because of Vite.

Thank you, I really appreciate you published this plugin!

**Comment by Siilwyn** [comment]
PostCSS is listed in the peer dependencies: https://github.com/Siilwyn/prettier-plugin-css-order/blob/0948dc87da298ee48fc38c2cfe11d4f5c0fb6b56/package.json#L23

Or do you mean something else?

**Comment by receter** [comment]
Hmm, then it's a issue with my eyes. Sorry for the inconvenience.

**Comment by receter** [comment]
This is `prettier` right?

**Comment by receter** [comment]
https://github.com/Siilwyn/prettier-plugin-css-order/pull/46

**Comment by Siilwyn** [comment]
Oh whoops sorry about that. Regarding `postcss`, I never call postcss directly from this codebase and it's a peer dependency of `css-declaration-sorter` (which is a dependency here). Peer dependencies are automatically installed with npm 7>, so I think we're good?

**Comment by receter** [comment]
Ok, this makes sense. It didn't work for me because I accidentally had `legacy-peer-deps=true` in my global `.npmrc`, glad I found this… must have been there a while already 😬

**Comment by Siilwyn** [comment]
Ah good find! Thank you for the thoughts on this I've removed `postcss` from the installation instruction too since it might be confusing and isn't needed in most cases.
